### ISSUE TITLE
Unread section not working with Categories since FreshRSS 1.10.0

### ISSUE THREAD

**Issue by GLLM** [Alkarex/EasyRSS#37] opened 2018-03-01 11:39 UTC
Hi,

I'm been using FreshRSS 1.09 with EasyRSS 0.6.08 (608) and all was fine.

Since I upgraded to FreshRSS 1.10 (Ubuntu 16.04 LTS + MySQL + PHP 7), EasyRSS is not able to load **unread** articles by **Categories** in the **Unread** section ...

I can see the unread items when browsing the feeds one by one, but when opening Categories : nothing loads !

I'm sad,
Thanks
G_LL_M

**Comment by Alkarex** [comment] 2018-03-01 14:01
Could be related to https://github.com/Alkarex/EasyRSS/issues/36 (already fixed in FreshRSS).
I will check.

**Comment by GLLM** [comment] 2018-03-01 15:33
Hey @Alkarex !
Thanks for the swift reply.
I'll check the #36 and monitor teh availabel updates ;)
thanks.

**Comment by Alkarex** [comment] 2018-03-01 19:40
I cannot reproduce the problem with the current /dev version of FreshRSS. EasyRSS works fine for me right now.
Maybe what you were experiencing was solved indirectly with https://github.com/FreshRSS/FreshRSS/pull/1800
Could you test the /dev version of FreshRSS?

**Comment by GLLM** [comment] 2018-03-02 11:30
Mmmh, I'll check but I only have my "prod" instance ...  I wouldn't want to mess it up :-(
Will try to see what I can do ...

**Comment by mnieke** [comment] 2018-03-04 21:10
I had the same issue. But with version 1.10.1 it works again. You should also be able to update it without using the dev version.

**Comment by GLLM** [comment] 2018-03-06 16:28
It's working again in 1.10.1 !! :) Cool ...
Thanks @Alkarex

**Closed** 2018-03-10 07:36 UTC
